### ISSUE TITLE
auto save ou pas ?

### ISSUE THREAD

**Issue by Thothore** [SnaKyEyeS/ADE-Scheduler#140]
**Is your feature request related to a problem? Please describe.**
Often I add an event on my phone, forget to save and then it's not here when I look up on my computer

**Describe the solution you'd like**
Once a calendar has been saved, turn auto save on so that when I add a custom event I won't have to manually save it every time

**Describe alternatives you've considered**
An option to turn on or off autosave

**Additional context**

**Comment by jeertmans** [comment]
Hello @Thothore , thanks for suggesting your idea !
Indeed the actual saving mechanism is prone to human errors and often leads to confusion.

We still need to think about that in team but where do you think this "toggle" (turn ON/OFF) button should be placed ?

**Comment by Thothore** [comment]
I'd say either here or there, what I had in mind was a sort of switch like that 
![image](https://user-images.githubusercontent.com/35405712/96105196-0eddac00-0eda-11eb-818e-7e657af4e2d8.png)

![image](https://user-images.githubusercontent.com/35405712/96105020-d63dd280-0ed9-11eb-850a-52fbf14ccc68.png)

![image](https://user-images.githubusercontent.com/35405712/96105277-2321a900-0eda-11eb-9493-f29a38177a90.png)

**Comment by jeertmans** [comment]
Ok thank you :)

I have started working on this. This will be released soon I hope, but we will need to also provide an option to activate "auto re-loading" I think (meaning that it loads the last schedule you have saved, which is not the case for the moment)
