### ISSUE TITLE
TP considered as CM

### ISSUE THREAD

**Issue by SachaDef** [SnaKyEyeS/ADE-Scheduler#318]
**Describe the bug**
A class that is a TP is actually considered by the scheduler as a CM.

**To Reproduce**
1. Create a new schedule and add either the 'FILIERE INFO 12' group of classes or the 'LELEC1370' class.
2. The class starts on week 1-7 February 2021, go to that week and you will have two CM's (Q4 & Q4.1), with one actually being a TP.

**Expected behavior**
Have the TP appear as a TP.

**Screenshots**
![img5](https://user-images.githubusercontent.com/65407167/105342838-26b38300-5be1-11eb-9a84-076fb169708d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (Family)
 - Browser: Chrome   &   OperaGX
 - Version: 88.0.4324.96   &   LVL2 (core: 72.0.3815.473)

**Smartphone (please complete the following information):**
Not tested

**Comment by SnaKyEyeS** [comment]
Thanks for this issue ! Sadly, this is something we're kinda aware of and which we cannot do much for since it's likely due to encoding error from the ADE API.

**Comment by SachaDef** [comment]
Didn't know for sure you were grabbing the data from the ADE API, but I figured it could be out of your hands.
Thanks anyway !

**Comment by SachaDef** [comment]
Dependent from ADE API

**Comment by SnaKyEyeS** [comment]
Actually, you can let the issue open so other people know what it is about (and we can sort of keep an eye on it if something changes on this side in the future-

**Comment by jeertmans** [comment]
Closing this since this problem has been solved (few weeks ago) by contacting the secretary ;)
