### ISSUE TITLE
New button for selecting or de-selecting all activities of one course

### ISSUE THREAD

**Issue by TomKenda** [SnaKyEyeS/ADE-Scheduler#383]
J’ai une petite proposition : 

il serait possible d’ajouter un boutont « sélectionner tout » ou « dé-séléctionner tout » pour quand on clique sur un cours et qu’il comprend beaucoup d’activité et qu’on en veux qu’une seul ? Pcq au fur et a mesure de l’année des nouvelle activités s’ajoute (exam, …) et elle sont automatiquement ajouter à mon programme alors que je les veux pas donc je dois aller dé-séléctionner tout manuellement.

PS : Notez que c'est utile juste pour le cas particulier du tronc commun agro master qui est probablement mal encodé dans ADE ce qui fait que tout les cours de tout les master bioingé se mettent dedans alors qu'il devrait contenir seulement les cours du tronc commun. Le code cours du tronc commun est : BIRA21M_TC si vous voulez voir 

![image001](https://user-images.githubusercontent.com/75068847/111873485-bb8fee00-8990-11eb-895b-ee98c328a067.png)

**Comment by jeertmans** [comment]
Hello Tom ! Merci d’avoir posté le message ici ;)

On en discutera prochainement avec les autres développeurs et on te tiendra au courant de la suite via ce post :)
