### ISSUE TITLE
Problème avec les jours

### ISSUE THREAD

**Issue by FelixGaudin** [SnaKyEyeS/ADE-Scheduler#424]
**Describe the bug**
Les jours indiqués en mode "mois" ne sont pas les memes que ceux en mode "semaine"
![Capture d’écran 2021-05-21 132441](https://user-images.githubusercontent.com/44848675/119130379-6fb50000-ba38-11eb-942b-b83e3d362b38.png)
![Capture d’écran 2021-05-21 132319](https://user-images.githubusercontent.com/44848675/119130393-72aff080-ba38-11eb-9f02-489b7968ce2b.png)

**To Reproduce**
1. Aller sur la semaine actuelle
2. Passer en mode mois
3. Bouger entre les mois (les jours de la semaines ne changent pas

**Expected behavior**
Les semaines devraient changer

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 88.0.1

**Smartphone (please complete the following information):**

**Comment by SnaKyEyeS** [comment]
Effectivement, j'ai réussi à reproduire chez moi... très bizarre tout ça ! Je vais essayer de regarder un peu si j'arrive à résoudre le problème... 
Merci pour ton message en tout cas :-)

**Comment by jeertmans** [comment]
C'est bizarre.. cela semble est déclenché via quand on va en vue "mois" et qu'on change de mois. @FelixGaudin quelle est la langue de ton navigateur internet ? Pour voir si ce serait lié à cela ou pas

**Comment by SnaKyEyeS** [comment]
Ça semble être fixé en passant sur la dernière version du FullCalendar (5.7, cfr la PR #439).
On déploiera sûrement ça cette après-midi :-)
