### ISSUE TITLE
NPX: lots of deprecation warnings

### ISSUE THREAD

**Issue by jeertmans** [SnaKyEyeS/ADE-Scheduler#440]
**Describe the bug**
`npm update` seems to find problems in the deps, and `npx webpack` alerts about many deprecations.

**To Reproduce**
1. `npm update` (ignore warnings)
<pre>(node:25399) ExperimentalWarning: The fs.promises API is experimental
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">EBADENGINE</font> Unsupported engine { package: &apos;human-signals@2.1.0&apos;,
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">EBADENGINE</font>   required: { node: &apos;&gt;=10.17.0&apos; },
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">EBADENGINE</font>   current: { node: &apos;v10.16.3&apos;, npm: &apos;7.9.0&apos; } }

added 22 packages, changed 2 packages, and audited 676 packages in 18s

63 packages are looking for funding
  run `npm fund` for details

3 <font color="#C4A000"><b>moderate</b></font> severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
</pre>
2. `npx webpack`: enjoy the deprecation warnings
3. `npm audit fix --force`: try to find the npm warnings
4. `npx webpack`:
<pre>(node:24870) ExperimentalWarning: The fs.promises API is experimental
[webpack-cli] <font color="#CC0000">Failed to load &apos;/home/jerome/Documents/programmation/ADE-Scheduler/webpack.config.js&apos; config</font>
[webpack-cli] <font color="#CC0000">{ Error: Cannot find module &apos;vue-loader/lib/plugin&apos;</font>
<font color="#CC0000">    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)</font>
<font color="#CC0000">    at Function.Module._load (internal/modules/cjs/loader.js:562:25)</font>
<font color="#CC0000">    at Module.require (internal/modules/cjs/loader.js:692:17)</font>
<font color="#CC0000">    at require (/home/jerome/Documents/programmation/ADE-Scheduler/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)</font>
<font color="#CC0000">    at Object.&lt;anonymous&gt; (/home/jerome/Documents/programmation/ADE-Scheduler/webpack.config.js:4:25)</font>
<font color="#CC0000">    at Module._compile (/home/jerome/Documents/programmation/ADE-Scheduler/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)</font>
<font color="#CC0000">    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)</font>
<font color="#CC0000">    at Module.load (internal/modules/cjs/loader.js:653:32)</font>
<font color="#CC0000">    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)</font>
<font color="#CC0000">    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: &apos;MODULE_NOT_FOUND&apos; }</font></pre>

**Expected behavior**
I wish we had no warning at all :')

**Comment by SnaKyEyeS** [comment]
Can we close this ?
