### ISSUE TITLE
Replacing Travis CI

### ISSUE THREAD

**Issue by SnaKyEyeS** [SnaKyEyeS/ADE-Scheduler#541]
Travis CI is no longer 100% free for Open Source project (there is a credit limit, one which we will eventually reach at some point - after ~200 builds from this point).
Therefore, we should look to migrate from Travis CI to another alternative. As a few starting suggestions:
 * Circle CI (free credits each month, should be plenty enough for us)
 * GitHub Action (GHA) - is completely free and would perfectly suit our needs as far as I can see.

**Comment by jeertmans** [comment]
RIP this explains why it stopped..

**Comment by SnaKyEyeS** [comment]
Nah, that was something else... the builds work now, but at some point (in about 200 builds), they will stop - hence the (not so urgent) need for an alternative.

**Comment by jeertmans** [comment]
After a few researches, GitHub actions seem to be a good alternative. Here is a document that describes how to transpose Travis CI testing into GitHub actions : https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions
