### ISSUE TITLE
Update save to save across platforms and browser for a same account

### ISSUE THREAD

**Issue by YannPollet** [SnaKyEyeS/ADE-Scheduler#590]
It takes time to recreate the same schedule on each browser I use. It's frustrating especially when you use several OS on your computer and ADE-scheduler on your phone.

It would be interesting to save the schedule on the server to update the schedule on each browser at once.

**Additional context**

**Comment by jeertmans** [comment]
Hello @YannPollet ,
If I understand well your problem, what you are looking for is provided by the "Account" feature. If you create an account, then everything is automatically synchronized (granted you saved your changes, still you can activate "auto-save" feature).

Do you have an account ?
